name: E2E environment
description: Sets up test environment for E2E tests.
inputs:
  version:
    description: WordPress version to install.
  amp:
    description: AMP plugin version to install.
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo systemctl start mysql.service
        mkdir /tmp/wp
        composer global require \
          wp-cli/wp-cli \
          wp-cli/core-command \
          wp-cli/config-command \
          wp-cli/server-command \
          wp-cli/rewrite-command \
          wp-cli/entity-command \
          wp-cli/extension-command \
          wp-cli/db-command
    - shell: bash
      working-directory: /tmp/wp
      run: |
        export PATH="$(composer config -g home)/vendor/bin:$PATH"
        wp core download --version=${{ inputs.version }} --force
        wp config create --dbname=wordpress_test --dbuser=root --dbpass=root
        wp db create
        wp core install --title="SiteKit" --admin_user=admin --admin_password=password --admin_email=test@test.com --skip-email --url=http://localhost:3306
    - shell: bash
      run: |
        cp -r --force tests/e2e/mu-plugins /tmp/wp/wp-content/mu-plugins
        cp -r --force tests/e2e/plugins /tmp/wp/wp-content/plugins
        cp -r --force $PWD /tmp/wp/wp-content/plugins/google-site-kit
    - shell: bash
      working-directory: /tmp/wp
      run: |
        export PATH="$(composer config -g home)/vendor/bin:$PATH"
        wp user create admin-2 admin-2@example.com --role=administrator --user_pass=password --quiet
        wp user create editor editor@example.com --role=editor --user_pass=password --quiet
        wp user create author author@example.com --role=author --user_pass=password --quiet
        wp user create contributor contributor@example.com --role=contributor --user_pass=password --quiet

        wp post create --post_status=publish --post_title="Hello Solar System!" --quiet
        wp post create --post_status=publish --post_title="Hello Milky Way!" --quiet
        wp post create --post_status=publish --post_title="Hello Universe!" --quiet
        wp post create --post_status=publish --post_title="Hello Spéçïåł čhāràćtęrß!" --quiet

        if [ ! -z "${{ inputs.amp }}" ]; then
          wp plugin install amp --force --version=${{ inputs.amp }}
        fi

        wp plugin activate google-site-kit
        wp rewrite structure '%postname%' --hard

        wp server --host=0.0.0.0 --port=9002 &
