{
  "discoveryVersion": "v1",
  "name": "adsense",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "basePath": "",
  "version_module": true,
  "id": "adsense:v2",
  "resources": {
    "accounts": {
      "methods": {
        "getAdBlockingRecoveryTag": {
          "description": "Gets the ad blocking recovery tag of an account.",
          "path": "v2/{+name}/adBlockingRecoveryTag",
          "id": "adsense.accounts.getAdBlockingRecoveryTag",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v2/accounts/{accountsId}/adBlockingRecoveryTag"
        },
        "get": {
          "description": "Gets information about the selected AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "path": "v2/{+name}",
          "flatPath": "v2/accounts/{accountsId}",
          "httpMethod": "GET",
          "id": "adsense.accounts.get"
        },
        "listChildAccounts": {
          "id": "adsense.accounts.listChildAccounts",
          "description": "Lists all accounts directly managed by the given AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "path": "v2/{+parent}:listChildAccounts",
          "httpMethod": "GET",
          "flatPath": "v2/accounts/{accountsId}:listChildAccounts"
        },
        "list": {
          "flatPath": "v2/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "path": "v2/accounts",
          "description": "Lists all accounts available to this user.",
          "id": "adsense.accounts.list",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "payments": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET",
              "path": "v2/{+parent}/payments",
              "description": "Lists all the payments available for an account.",
              "id": "adsense.accounts.payments.list",
              "flatPath": "v2/accounts/{accountsId}/payments"
            }
          }
        },
        "alerts": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "adsense.accounts.alerts.list",
              "flatPath": "v2/accounts/{accountsId}/alerts",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Lists all the alerts available in an account.",
              "path": "v2/{+parent}/alerts"
            }
          }
        },
        "sites": {
          "methods": {
            "get": {
              "flatPath": "v2/accounts/{accountsId}/sites/{sitesId}",
              "path": "v2/{+name}",
              "id": "adsense.accounts.sites.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Gets information about the selected site."
            },
            "list": {
              "id": "adsense.accounts.sites.list",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET",
              "path": "v2/{+parent}/sites",
              "description": "Lists all the sites available in an account.",
              "flatPath": "v2/accounts/{accountsId}/sites"
            }
          }
        },
        "policyIssues": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.policyIssues.get",
              "path": "v2/{+name}",
              "httpMethod": "GET",
              "flatPath": "v2/accounts/{accountsId}/policyIssues/{policyIssuesId}",
              "description": "Gets information about the selected policy issue."
            },
            "list": {
              "httpMethod": "GET",
              "id": "adsense.accounts.policyIssues.list",
              "flatPath": "v2/accounts/{accountsId}/policyIssues",
              "path": "v2/{+parent}/policyIssues",
              "description": "Lists all the policy issues where the specified account is involved, both directly and through any AFP child accounts.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            }
          }
        },
        "adclients": {
          "resources": {
            "adunits": {
              "methods": {
                "listLinkedCustomChannels": {
                  "path": "v2/{+parent}:listLinkedCustomChannels",
                  "id": "adsense.accounts.adclients.adunits.listLinkedCustomChannels",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists all the custom channels available for an ad unit.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}:listLinkedCustomChannels",
                  "httpMethod": "GET"
                },
                "create": {
                  "description": "Creates an ad unit. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method. Note that ad units can only be created for ad clients with an \"AFC\" product code. For more info see the [AdClient resource](/adsense/management/reference/rest/v2/accounts.adclients). For now, this method ca[...]",
                  "id": "adsense.accounts.adclients.adunits.create",
                  "path": "v2/{+parent}/adunits",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits"
                },
                "get": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.adunits.get",
                  "description": "Gets an ad unit from a specified account and ad client.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "path": "v2/{+name}"
                },
                "patch": {
                  "id": "adsense.accounts.adclients.adunits.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "description": "Updates an ad unit. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method. For now, this method can only be used to update `DISPLAY` ad units. See: https://support.google.com/adsense/answer/9183566",
                  "httpMethod": "PATCH",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "path": "v2/{+name}"
                },
                "list": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits",
                  "description": "Lists all ad units under a specified account and ad client.",
                  "httpMethod": "GET",
                  "path": "v2/{+parent}/adunits",
                  "id": "adsense.accounts.adclients.adunits.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "getAdcode": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Gets the ad unit code for a given ad unit. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634) and [Where to place the ad code in your HTML](https://support.google.com/adsense/answer/9190028).",
                  "path": "v2/{+name}/adcode",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}/adcode",
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.adunits.getAdcode"
                }
              }
            },
            "urlchannels": {
              "methods": {
                "get": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels/{urlchannelsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "path": "v2/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets information about the selected url channel.",
                  "id": "adsense.accounts.adclients.urlchannels.get"
                },
                "list": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels",
                  "id": "adsense.accounts.adclients.urlchannels.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "path": "v2/{+parent}/urlchannels",
                  "description": "Lists active url channels."
                }
              }
            },
            "customchannels": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.customchannels.get",
                  "path": "v2/{+name}",
                  "description": "Gets information about the selected custom channel.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "httpMethod": "GET"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels",
                  "description": "Lists all the custom channels available in an ad client.",
                  "path": "v2/{+parent}/customchannels",
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.customchannels.list"
                },
                "delete": {
                  "description": "Deletes a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method.",
                  "path": "v2/{+name}",
                  "id": "adsense.accounts.adclients.customchannels.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "adsense.accounts.adclients.customchannels.patch",
                  "path": "v2/{+name}",
                  "description": "Updates a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}"
                },
                "create": {
                  "description": "Creates a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "path": "v2/{+parent}/customchannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels",
                  "httpMethod": "POST",
                  "id": "adsense.accounts.adclients.customchannels.create"
                },
                "listLinkedAdUnits": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}:listLinkedAdUnits",
                  "httpMethod": "GET",
                  "path": "v2/{+parent}:listLinkedAdUnits",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists all the ad units available for a custom channel.",
                  "id": "adsense.accounts.adclients.customchannels.listLinkedAdUnits"
                }
              }
            }
          },
          "methods": {
            "get": {
              "id": "adsense.accounts.adclients.get",
              "path": "v2/{+name}",
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}",
              "httpMethod": "GET",
              "description": "Gets the ad client from the given resource name.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            },
            "getAdcode": {
              "id": "adsense.accounts.adclients.getAdcode",
              "description": "Gets the AdSense code for a given ad client. This returns what was previously known as the 'auto ad code'. This is only supported for ad clients with a product_code of AFC. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634).",
              "path": "v2/{+name}/adcode",
              "httpMethod": "GET",
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adcode",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            },
            "list": {
              "id": "adsense.accounts.adclients.list",
              "description": "Lists all the ad clients available in an account.",
              "flatPath": "v2/accounts/{accountsId}/adclients",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "path": "v2/{+parent}/adclients"
            }
          }
        },
        "reports": {
          "methods": {
            "generateCsv": {
              "httpMethod": "GET",
              "description": "Generates a csv formatted ad hoc report.",
              "path": "v2/{+account}/reports:generateCsv",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "flatPath": "v2/accounts/{accountsId}/reports:generateCsv",
              "id": "adsense.accounts.reports.generateCsv"
            },
            "generate": {
              "description": "Generates an ad hoc report.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.reports.generate",
              "httpMethod": "GET",
              "flatPath": "v2/accounts/{accountsId}/reports:generate",
              "path": "v2/{+account}/reports:generate"
            },
            "getSaved": {
              "httpMethod": "GET",
              "path": "v2/{+name}/saved",
              "description": "Gets the saved report from the given resource name.",
              "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved",
              "id": "adsense.accounts.reports.getSaved",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            }
          },
          "resources": {
            "saved": {
              "methods": {
                "generateCsv": {
                  "description": "Generates a csv formatted saved report.",
                  "httpMethod": "GET",
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generateCsv",
                  "id": "adsense.accounts.reports.saved.generateCsv",
                  "path": "v2/{+name}/saved:generateCsv",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "generate": {
                  "id": "adsense.accounts.reports.saved.generate",
                  "description": "Generates a saved report.",
                  "path": "v2/{+name}/saved:generate",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generate"
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "path": "v2/{+parent}/reports/saved",
                  "description": "Lists saved reports.",
                  "flatPath": "v2/accounts/{accountsId}/reports/saved",
                  "id": "adsense.accounts.reports.saved.list"
                }
              }
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://adsense.googleapis.com/",
  "description": "The AdSense Management API allows publishers to access their inventory and run earnings and performance reports.",
  "title": "AdSense Management API",
  "batchPath": "batch",
  "version": "v2",
  "ownerName": "Google",
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/adsense/management/",
  "revision": "20251210",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adsense.readonly": {
          "description": "View your AdSense data"
        },
        "https://www.googleapis.com/auth/adsense": {
          "description": "View and manage your AdSense data"
        }
      }
    }
  },
  "mtlsRootUrl": "https://adsense.mtls.googleapis.com/",
  "rootUrl": "https://adsense.googleapis.com/",
  "ownerDomain": "google.com"
}
