export default {
	admin: {
		siteURL: 'https://example.com',
		siteName: 'My Great Blog',
		siteUserID: 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4',
		adminRoot: 'https://example.com/wp-admin/admin.php',
		assetsRoot: '/',
		nojscache: false,
		timestamp: 1595964258,
		currentScreen: {
			action: '',
			base: 'toplevel_page_googlesitekit-dashboard',
			id: 'toplevel_page_googlesitekit-dashboard',
			is_network: false,
			is_user: false,
			parent_base: null,
			parent_file: null,
			post_type: '',
			taxonomy: '',
			is_block_editor: false,
		},
		currentAdminPage: 'googlesitekit-dashboard',
		resetSession: null,
		reAuth: null,
		userData: {
			id: 1,
			email: 'wapuu.wordpress@gmail.com',
			name: 'Wapuu WordPress',
			picture: '',
		},
		ampEnabled: false,
		ampMode: false,
		homeURL: 'https://example.com',
		newSitePosts: '0',
		proxySetupURL: 'https://sitekit.withgoogle.com/site-management/setup/?scope=openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fsiteverification%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fwebmasters%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fanalytics.readonly&supports=credentials_retrieval%20short_verification_token%20file_verification&nonce=685074d315&site_id=DgLbbWgbQAEfYojMsHAu9N-Hc8zvNvKDMQZska2VdF3Pm.apps.sitekit.withgoogle.com&mode=analytics-step&user_roles=administrator&application_name=wordpress%2Fgoogle-site-kit%2F1.12.0&hl=en_US',
		proxyPermissionsURL: 'https://sitekit.withgoogle.com/site-management/permissions/?token=ya29.a0AfH6SMBKMDp-xCya_tCFPiYBouArLyls5wEZj-YGiCer44YNEgFd5r9G83lm5EsD-w17Oj6qGKCUzUN6rOsiBfVpYkQzcdRFfKNAFPE5rcTQ-XR6IF8n9R74VRlaac6iCTfwRO18KX_7b4Xs8CDr4VWtIB9FwPrLnqY&site_id=DgLbbWgbQAEfYojMsHAu9N-Hc8zvNvKDMQZska2VdF3Pm.apps.sitekit.withgoogle.com&application_name=wordpress%2Fgoogle-site-kit%2F1.12.0',
		connectURL: 'https://example.com/wp-admin/admin.php?page=googlesitekit-splash&googlesitekit_connect=1&nonce=e6677e47c0',
		disconnectURL: 'https://example.com/wp-admin/admin.php?page=googlesitekit-splash&googlesitekit_disconnect=1&nonce=f3b39eb3e0',
	},
	modules: {
		'site-verification': {
			slug: 'site-verification',
			name: 'Site Verification',
			description: 'Google Site Verification allows you to manage ownership of your site.',
			cta: 'Verify ownership with Google Site Verification.',
			sort: 0,
			homepage: 'https://www.google.com/webmasters/verification/home',
			learnMore: 'https://developers.google.com/site-verification/',
			group: '',
			feature: '',
			module_tags: [],
			required: [],
			autoActivate: true,
			internal: true,
			screenID: false,
			settings: false,
			active: true,
			setupComplete: true,
			dependencies: [],
			dependants: [],
		},
		'search-console': {
			slug: 'search-console',
			name: 'Search Console',
			description: 'Google Search Console and helps you understand how Google views your site and optimize its performance in search results.',
			cta: 'Connect your site to Google Search Console.',
			sort: 1,
			homepage: 'https://search.google.com/search-console',
			learnMore: 'https://search.google.com/search-console/about',
			group: '',
			feature: '',
			module_tags: [],
			required: [],
			autoActivate: true,
			internal: false,
			screenID: 'googlesitekit-module-search-console',
			settings: { propertyID: 'https://example.com/' },
			active: true,
			setupComplete: true,
			dependencies: [],
			dependants: [],
		},
		adsense: {
			slug: 'adsense',
			name: 'AdSense',
			description: 'Earn money by placing ads on your website. It\u2019s free and easy.',
			cta: 'Monetize Your Site.',
			sort: 2,
			homepage: 'https://www.google.com/adsense/start?source=site-kit&url=https://example.com',
			learnMore: 'https://www.google.com/intl/en_us/adsense/start/',
			group: 'Additional Google Services',
			feature: '',
			module_tags: [ 'monetize' ],
			required: [],
			autoActivate: false,
			internal: false,
			screenID: 'googlesitekit-module-adsense',
			settings: {
				accountID: '',
				clientID: '12345678.apps.googleusercontent.com',
				accountStatus: '',
				siteStatus: '',
				accountSetupComplete: false,
				siteSetupComplete: false,
				useSnippet: true,
			},
			provides: [
				'Monetize your website',
				'Intelligent, automatic ad placement',
			],
			accountURL: 'https://www.google.com/adsense/signup/new?source=site-kit&url=https%3A%2F%2Fexample.com',
			signupURL: 'https://www.google.com/adsense/signup/new?source=site-kit&url=https%3A%2F%2Fexample.com&utm_source=site-kit&utm_medium=wordpress_signup',
			rootURL: 'https://www.google.com/adsense/?source=site-kit&url=https%3A%2F%2Fexample.com',
			active: false,
			setupComplete: false,
			dependencies: [],
			dependants: [],
		},
		analytics: {
			slug: 'analytics',
			name: 'Analytics',
			description: 'Get a deeper understanding of your customers. Google Analytics gives you the free tools you need to analyze data for your business in one place.',
			cta: 'Get to know your customers.',
			sort: 3,
			homepage: 'https://analytics.google.com/analytics/web',
			learnMore: 'https://marketingplatform.google.com/about/analytics/',
			group: 'Marketing Platform',
			feature: '',
			module_tags: [],
			required: [],
			autoActivate: false,
			internal: false,
			screenID: 'googlesitekit-module-analytics',
			settings: {
				accountID: 'XXXXXXXX',
				adsenseLinked: false,
				anonymizeIP: true,
				internalWebPropertyID: 'XXXXXXXX',
				profileID: 'XXXXXXXX',
				propertyID: 'UA-XXXXXXXX-X',
				trackingDisabled: [ 'loggedinUsers' ],
				useSnippet: true,
			},
			provides: [ 'Audience overview', 'Top pages', 'Top acquisition channels' ],
			active: true,
			setupComplete: true,
			dependencies: [],
			dependants: [ 'optimize', 'tagmanager' ],
		},
		'pagespeed-insights': {
			slug: 'pagespeed-insights',
			name: 'PageSpeed Insights',
			description: 'Google PageSpeed Insights gives you metrics about performance, accessibility, SEO and PWA.',
			cta: 'Learn more about your website\u2019s performance.',
			sort: 4,
			homepage: 'https://developers.google.com/speed/pagespeed/insights/',
			learnMore: 'https://developers.google.com/speed/docs/insights/v5/about',
			group: 'Additional Google Services',
			feature: '',
			module_tags: [],
			required: [],
			autoActivate: false,
			internal: false,
			screenID: false,
			settings: false,
			provides: [ 'Website performance reports for mobile and desktop' ],
			active: true,
			setupComplete: true,
			dependencies: [],
			dependants: [],
		},
		optimize: {
			slug: 'optimize',
			name: 'Optimize',
			description: 'Create free A/B tests that help you drive metric-based design solutions to your site.',
			cta: 'Increase your CTR.',
			sort: 5,
			homepage: 'https://optimize.google.com/optimize/home/',
			learnMore: 'https://marketingplatform.google.com/about/optimize/',
			group: 'Marketing Platform',
			feature: '',
			module_tags: [ 'marketing' ],
			required: [ 'analytics' ],
			autoActivate: false,
			internal: false,
			screenID: false,
			settings: { ampExperimentJSON: '', optimizeID: '' },
			provides: [
				'A/B or multivariate testing',
				'Improvement tracking',
				'Probability and confidence calculations',
			],
			active: false,
			setupComplete: false,
			dependencies: [ 'analytics' ],
			dependants: [],
		},
		tagmanager: {
			slug: 'tagmanager',
			name: 'Tag Manager',
			description: 'Tag Manager creates an easy to manage way to create tags on your site without updating code.',
			cta: 'Tag management made simple.',
			sort: 6,
			homepage: 'https://tagmanager.google.com/',
			learnMore: 'https://marketingplatform.google.com/about/tag-manager/',
			group: 'Marketing Platform',
			feature: '',
			module_tags: [ 'marketing' ],
			required: [ 'analytics' ],
			autoActivate: false,
			internal: false,
			screenID: false,
			settings: {
				accountID: '',
				ampContainerID: '',
				containerID: '',
				internalContainerID: '',
				internalAMPContainerID: '',
				useSnippet: true,
			},
			provides: [ 'Create tags without updating code' ],
			active: false,
			setupComplete: false,
			dependencies: [ 'analytics' ],
			dependants: [],
		},
	},
	locale: 'en_US',
	permissions: {
		canAuthenticate: true,
		canSetup: true,
		canViewPostsInsights: true,
		canViewDashboard: true,
		canViewModuleDetails: true,
		canManageOptions: true,
		canPublishPosts: true,
	},
	setup: {
		isSiteKitConnected: true,
		isResettable: true,
		isAuthenticated: true,
		requiredScopes: [
			'openid',
			'https://www.googleapis.com/auth/userinfo.profile',
			'https://www.googleapis.com/auth/userinfo.email',
			'https://www.googleapis.com/auth/siteverification',
			'https://www.googleapis.com/auth/webmasters',
			'https://www.googleapis.com/auth/analytics.readonly',
		],
		grantedScopes: [
			'openid',
			'https://www.googleapis.com/auth/userinfo.profile',
			'https://www.googleapis.com/auth/userinfo.email',
			'https://www.googleapis.com/auth/siteverification',
			'https://www.googleapis.com/auth/webmasters',
			'https://www.googleapis.com/auth/analytics.readonly',
		],
		unsatisfiedScopes: [],
		needReauthenticate: false,
		isVerified: true,
		isFirstAdmin: true,
		hasSearchConsoleProperty: true,
		showModuleSetupWizard: null,
		moduleToSetup: '',
	},
	notifications: [],
	permaLink: false,
	pageTitle: '',
	postID: false,
	postType: false,
	dashboardPermalink: 'https://example.com/wp-admin/admin.php?page=googlesitekit-dashboard',
	publicPath: 'https://example.com/wp-content/plugins/google-site-kit/dist/assets/js/',
	editmodule: null,
};
