name: E2E Tests

on:
  push:
    branches:
      - develop
      - main
    # Ignore Storybook-only and unit-test-only changes when checking to run
    # E2E tests. This is useful when adding/modifying/refactoring/removing
    # test code ONLY in a commit, but saves running the expensive E2E test
    # suite on GitHub Actions when all that's changing are tests and not code
    # that would affect E2E behavior.
    paths:
      - '.github/workflows/e2e-tests.yml'
      - '.babelrc'
      - 'assets/**'
      - 'includes/**'
      - '*.php'
      - 'jest-puppeteer.config.js'
      - 'composer.json'
      - 'composer.lock'
      - 'php-scoper/composer.lock'
      - 'package.json'
      - 'package-lock.json'
      - 'postcss.config.js'
      - 'webpack/*.config.js'
      - 'webpack.config.js'
      - 'tests/e2e/**'
      - '!assets/**/__tests__/**/*.js'
      - '!assets/**/test/*.js'
      - '!assets/**/*.test.js'
      - '!packages/**/__tests__/**/*.js'
      - '!packages/**/test/*.js'
      - '!packages/**/*.test.js'
  pull_request:
    branches:
      - develop
      - main
      - 'feature/**'
    # Ignore Storybook-only and unit-test-only changes when checking to run
    # E2E tests. This is useful when adding/modifying/refactoring/removing
    # test code ONLY in a commit, but saves running the expensive E2E test
    # suite on GitHub Actions when all that's changing are tests and not code
    # that would affect E2E behavior.
    paths:
      - '.github/workflows/e2e-tests.yml'
      - '.babelrc'
      - 'assets/**'
      - 'includes/**'
      - '*.php'
      - 'jest-puppeteer.config.js'
      - 'composer.json'
      - 'composer.lock'
      - 'php-scoper/composer.lock'
      - 'package.json'
      - 'package-lock.json'
      - 'postcss.config.js'
      - 'webpack/*.config.js'
      - 'webpack.config.js'
      - 'tests/e2e/**'
      - '!assets/**/__tests__/**/*.js'
      - '!assets/**/test/*.js'
      - '!assets/**/*.test.js'
      - '!packages/**/__tests__/**/*.js'
      - '!packages/**/test/*.js'
      - '!packages/**/*.test.js'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: e2e-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-tests:
    name: E2E (WordPress ${{ matrix.wp_version }}${{ matrix.amp_version && ', AMP ' }}${{ matrix.amp_version }})
    strategy:
      fail-fast: false
      matrix:
        amp_version: ['']
        wp_version: ['latest', 'nightly']
        ca_cert_refresh: ['']
        include:
          - amp_version: '1.5.5'
            wp_version: '5.2.21'
            ca_cert_refresh: true
    env:
      AMP_VERSION: ${{ matrix.amp_version }}
      WP_VERSION: ${{ matrix.wp_version }}
      CA_CERT_REFRESH: ${{ matrix.ca_cert_refresh }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name == 'push' || github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      # - name: Install Chrome
      #   uses: browser-actions/setup-chrome@2e1d749697dd1612b833dba4a722266286fbefcd # ratchet:browser-actions/setup-chrome@v2.1.2
      #   with:
      #     chrome-version: 'latest'

      - name: npm install
        run: npm ci --workspaces --include-workspace-root

      - run: ls -al node_modules/puppeteer/.local-chromium

      - name: Remove Puppeteer's bundled Chromium
        run: rm -rf node_modules/puppeteer/.local-chromium

      - name: Build
        run: npm run build:test

      # E2E tests use a dedicated container, this is just for Composer.
      - uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # ratchet:shivammathur/setup-php@v2
        with:
          php-version: '8.4'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # ratchet:actions/cache@v5
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Composer Install
        run: composer install --no-interaction --no-progress --no-dev

      - name: Start environment
        run: npm run env:start

      - name: Run the tests
        run: npm run test:e2e

      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # ratchet:actions/upload-artifact@v6
        if: failure()
        with:
          name: e2e-debugging-run[${{ github.run_attempt }}]-wp[${{ matrix.wp_version }}]-amp[${{ matrix.amp_version }}]
          path: |
            ~/.npm/_logs/
            tests/e2e/screenshots/
