name: Publish VRT Docker Image

on:
  push:
    branches:
      - develop
    paths:
      - 'tests/backstop/Dockerfile'
      - '.github/workflows/publish-vrt-docker-image.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: google-site-kit-bot
          password: ${{ secrets.GH_BOT_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          # Update the version number here when updating the Backstop version within the Dockerfile.
          tags: ghcr.io/google/site-kit-wp/vrt:6.3.25
          context: ./tests/backstop
          push: true
          platforms: linux/amd64,linux/arm64
