name: Visual Regression Testing

on:
  pull_request:
    branches:
      - main
      - develop
      - 'feature/**'
    # Only run if CSS/JS related files changed.
    paths:
      - '.github/workflows/visual-regression.yml'
      - 'assets/**'
      - '!assets/**/__tests__/**/*.js'
      - '!assets/**/test/*.js'
      - '!assets/**/*.test.js'
      - '**.stories.js'
      - 'tests/backstop/**'
      - 'storybook/**'
      - '**.scss'
      - '.nvmrc'
      - '**/package.json'
      - 'package-lock.json'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: visual-regression-${{ github.ref }}
  cancel-in-progress: true

jobs:
  visual-regression:
    name: Run VR Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Setup Node.js (.nvmrc)
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # ratchet:actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: npm install
        run: npm ci -w assets -w tests/backstop -w storybook -w tests/js --include-workspace-root
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # ratchet:docker/login-action@v4
        with:
          registry: ghcr.io
          username: google-site-kit-bot
          password: ${{ secrets.GH_BOT_TOKEN }}
      - name: Run Backstopjs
        run: npm run test:visualtest
      - name: Upload artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # ratchet:actions/upload-artifact@v6
        if: failure()
        with:
          name: vrt-report
          path: |
            tests/backstop/ci_report
            tests/backstop/html_report
            tests/backstop/json_report
            tests/backstop/reference
            tests/backstop/tests
