name: Workflow Validation

on:
  pull_request:
    paths:
      - '.github/**.yml'

concurrency:
  group: workflow-validation-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-actions:
    name: Lint Actions
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-actionlint@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # Neither inline shellcheck nor `actionlint_flags`
          # disable a rule, so this must be disabled using
          # an env variable.
          SHELLCHECK_OPTS: "-e SC2129"
